use_frameworks!

platform :ios, '9.0'

target 'CollectionViewSegmentedControl_Example' do
  pod 'CollectionViewSegmentedControl', :path => '../'

  target 'CollectionViewSegmentedControl_Tests' do
    inherit! :search_paths

    
  end
end
